apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pd-balanced
parameters:
  type: pd-balanced
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer