# Default values for portainer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# If enterpriseEdition is enabled, then use the values below _instead_ of those in .image
enterpriseEdition: 
  enabled: false
  image:
    repository: portainer/portainer-ee
    tag: 2.19.5
    pullPolicy: Always

image:
  repository: portainer/portainer-ce
  tag: 2.19.2
  pullPolicy: Always

imagePullSecrets: []

nodeSelector:
  cloud.google.com/gke-nodepool: default-pool

serviceAccount:
  annotations: {}
  name: portainer-sa-clusteradmin

service:
  type: ClusterIP
  httpPort: 9000
  httpsPort: 9443
  # NodePort 설정은 필요하지 않으므로 주석 처리하거나 삭제
  # httpNodePort: 30777
  # httpsNodePort: 30779
  # edgePort: 8000
  # edgeNodePort: 30776
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"http":"backendconfig-portainer-server"}}'


tls:
  # If set, Portainer will be configured to use TLS only
  force: false
  # If set, will mount the existing secret into the pod
  existingSecret: ""

mtls:
  # If set, Portainer will be configured to use mTLS only
  enable: false
  # If set, will mount the existing secret into the pod
  existingSecret: ""

feature:
  flags: []

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # Only use below if tls.force=true
    # nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  # Note: Hosts and paths are of type array
  hosts:
    - host:
      paths: []
      # - path: "/"
  tls: []

resources: {}

persistence:
  enabled: true
  size: "10Gi"
  annotations: {}
  storageClass: pd-balanced
  existingClaim:

