apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: portainer-mcrt
spec:
  domains:
    - portainer.stancloud.shop
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  labels:
    env: prod
    region: asia-northeast3
    service: portainer    
  name: backendconfig-portainer-server
  namespace: portainer
spec:
  healthCheck:
    checkIntervalSec: 30
    healthyThreshold: 1
    timeoutSec: 5
    type: HTTP
    unhealthyThreshold: 2
    port: 9090
    requestPath: /
  logging:
    enable: true
    sampleRate: 1
  securityPolicy:
    name: cap-mkt-prod-stancloud-portainer
  sessionAffinity:
    affinityType: CLIENT_IP
  timeoutSec: 3600
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  labels:
    env: prod
    region: asia-northeast3  
    service: portainer  
  name: frontendconfig-portainer-server
  namespace: portainer
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: "301"
  sslPolicy: computesslpolicy-portainer-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: eip-elb-prod-portainer-server
    networking.gke.io/v1beta1.FrontendConfig: "frontendconfig-portainer-server"
    networking.gke.io/managed-certificates: portainer-mcrt
  labels:
    env: prod
    region: asia-northeast3
    service: portainer    
  name: elb-mkt-prod-wish-portainer
  namespace: portainer
spec:
  rules:
  - host: portainer.stancloud.shop
    http:
      paths:
      - backend:
          service:
            name: portainer
            port:
              number: 9090
        path: "/"
        #pathType: ImplementationSpecific
        pathType: Prefix
